### ISSUE TITLE
Met, Exhibition History by API

### ISSUE THREAD

**Issue by salvo-vitale** [rednaw/exhibitionDB#61]
Sarebbe utile verificare la possibilità di accedere ai dati delle Exhibition History di ogni singola opera attraverso Api.
https://www.metmuseum.org/art/collection/search/436173?searchField=All&amp;sortBy=Relevance&amp;high=on&amp;ao=on&amp;ft=degas&amp;offset=0&amp;rpp=20&amp;pos=3 
Questo il link di una pagina con Exhibition History

**Comment by rednaw** [comment]
Sito interessante che fa qualcosa di simile

https://ryanabest.com/work/MigrationOfArt/

**Comment by rednaw** [comment]
Il modo in cui ha realizzato questo progetto suggerisce che non è possibile ottenere una cronologia dell'opera d'arte direttamente dall'API Metropolitan

Menziona

> La principale sfida dei dati in questo progetto era come analizzare la storia della proprietà e delle mostre, che sono organizzate come paragrafi ed elenchi separati nell'API del Met e nella pagina Web front-end, in una storia coerente di movimento per ogni dipinto.

Ciò significa 'screen scraping' non 'utilizzo dell'API'

**Comment by rednaw** [comment]
Inoltre ho fatto delle ricerche e non ho trovato alcun riferimento alla storia (mostra) di un'opera d'arte nell'API Metropolitan

**Comment by rednaw** [comment]
Chiudo questo issue perché non è possibile ottenere informazioni storiche dall'API Met, vedere i miei commenti sopra.
