### ISSUE TITLE
Esempio di Ricerca per Artista

### ISSUE THREAD

**Issue by salvo-vitale** [rednaw/exhibitionDB#66]
Ecco una sequenza di screenshot che trovo semplici e intuitivi.

_Schermata Ricerca Artista_

![Schermata Ricerca Artista](https://user-images.githubusercontent.com/87476530/148110152-e8e5e40e-2b56-42f9-9c06-5b5744f19828.png)

_Schermata Lista Artisti trovati_

![Schermata Lista Artisti trovati](https://user-images.githubusercontent.com/87476530/148110187-865018c4-f900-4845-b1c7-5876c414d86a.png)

_Schermata Lista Esposizioni per l'Artista Hayez_

![Schermata Lista Esp per Hayez](https://user-images.githubusercontent.com/87476530/148110206-d4d11dc9-58b8-4efd-8520-fe2689a17660.png)

_Schermata delle Opere contenute nella prima Esposizione della Lista_

![Schermata Opere di Hayez nella Esp prima della lista](https://user-images.githubusercontent.com/87476530/148110216-8c41deb4-0067-40e5-b1fd-60841f147efa.png)

Non è perfetto e si può modificare ma mi sembra un buon punto da cui partire.

**Comment by rednaw** [comment]
Molto chiaro, questo caso d'uso è: 
1. "sfocato" cerca artista per nome
2. seleziona un artista specifico
3. visualizza le mostre per quell'artista
4. visualizza i dettagli di una mostra specifica

Posso implementarlo senza problemi, non è difficile. È importante però essere consapevoli in anticipo di altre domande che si potrebbero porre al nostro sistema.

Per esempio
1. "sfocato" cerca opere d'arte per nome
2. seleziona un'opera d'arte specifica
3. visualizza le mostre per quell'opera d'arte
4. visualizzare i dettagli di una mostra specifica

o domande simile come: 
1. quali artisti hanno avuto mostre in un luogo specifico? 
2. In quali paesi (o anni) è stata esposta questa opera d'arte?
3. ecc.

In generale: gli esempi più realistici di domande che i nostri utenti potrebbero porre, meglio è.

**Comment by rednaw** [comment]
Chiusura di questo issue perché è stato implementato
